# .github/ISSUE_TEMPLATE/slice.yml
- type: textarea
  id: tests
  attributes:
    label: Test notes (TDD)
    description: "Which unit tests and e2e tests will we add/update? Reference test IDs."
    placeholder: |
      Unit:
      - src/features/screener/__tests__/cohortAssignment.test.ts

      E2E:
      - BM-E2E-01 – AI-heavy screener happy path
  validations:
    required: false

- type: textarea
  id: telemetry
  attributes:
    label: Telemetry hooks
    description: "What events/properties must be emitted in this slice?"
    placeholder: "- Fire event screenerSubmitted with { cohort_label, preferred_channel }"
  validations:
    required: false

- type: textarea
  id: notes
  attributes:
    label: Notes / open questions
    description: "Any design questions, debt deferrals, or follow-ups."
    placeholder: "- TBD: refine error copy for Twilio timeouts\n- Future: add ES-only prompt variant"
  validations:
    required: false